### ISSUE TITLE
WordPress Coding Standards

### ISSUE THREAD

**Issue by robertdevore** [wpdispensary/wp-dispensary#1]
I am working through each release to go over every file in the plugin and bring all coding up to WordPress Coding Standards.

The goal is to have all files done by the release of Version 2.0

**Comment by pattonwebz** [comment]
I made a PR fixing some of the messages thrown by the WordPress standard and PHPCS.

I can spend a little more time on more of the issues in the coming days however there are a few things I spotted that would need reworked to silence the messages. I'll open additional issues for those items if I have time :)

**Comment by deviodigital** [comment]
Thanks, I appreciate it 🙌

I'll check the PR out asap and get it merged

**Comment by pattonwebz** [comment]
No sweat :+1: 

I kept the plugin installed on my test site and rechecked it was still working between changes - but it is not extensively tested so merge with care lol Due to many line ending changes the diff reports here don't make it clear initially what code is changed :s

**Comment by lucprincen** [comment]
@pattonwebz definitely willing to help with unit-tests. With WP CLI you can generate a fully functional starting point with this command:

`wp scaffold plugin-tests`

**Comment by pattonwebz** [comment]
@lucprincen if you have time to make a start on adding in some tests I'll join in when I get some spare time :)

**Comment by deviodigital** [comment]
@lucprincen @pattonwebz as a developer who knows very little about unit tests, I welcome any help you have the time to give 🙌💯
