### ISSUE TITLE
Not an issue, help wanted

### ISSUE THREAD

**Issue by ipankajthakur** [wpdispensary/wp-dispensary#16]
I want to show the subcategories of product below the titles in the product listing on home page, can you please help me how can I do that?

**Comment by robertdevore** [comment]
You're talking about with the shortcodes added to the "Dispensary Menu" page, correct?

If so, you can add category="name-here" to the shortcode, and it'll display only the menu items that are within that specific category (or categories, separated with a comma).

**Comment by ipankajthakur** [comment]
Ah no, I am talking about to show the category name in the front end.

**Comment by robertdevore** [comment]
ok, so if you have the FLOWERS section, you want the category name displayed under the flower image/title?

**Comment by ipankajthakur** [comment]
Yes, exactly.

**Comment by ipankajthakur** [comment]
in each product for each category

**Comment by robertdevore** [comment]
It's currently not an option built into the shortcodes. Would be happy to accept a PR if it's something you'd like to contribute :+1:
